# Generated by Django 3.2.12 on 2022-04-13 06:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg', models.TextField()),
                ('date', models.DateField()),
                ('fid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login1', to='monitor.login')),
                ('tid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login2', to='monitor.login')),
            ],
        ),
    ]
