# Generated by Django 3.2.12 on 2022-04-19 04:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0002_chat'),
    ]

    operations = [
        migrations.CreateModel(
            name='parent_tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=20)),
                ('mname', models.CharField(max_length=20)),
                ('lname', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=20)),
                ('phone', models.BigIntegerField()),
                ('stud_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitor.student_tb')),
            ],
        ),
        migrations.CreateModel(
            name='marks_tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.CharField(max_length=90)),
                ('date', models.CharField(max_length=40)),
                ('stud_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitor.student_tb')),
                ('sub_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitor.subject_tb')),
            ],
        ),
    ]
