# Generated by Django 3.2.12 on 2022-04-19 05:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0003_marks_tb_parent_tb'),
    ]

    operations = [
        migrations.AddField(
            model_name='parent_tb',
            name='log_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='monitor.login'),
            preserve_default=False,
        ),
    ]
