# Generated by Django 3.2.12 on 2022-04-22 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0004_parent_tb_log_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='books_tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=60)),
                ('book', models.FileField(upload_to='books')),
            ],
        ),
    ]
